/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mati' at '31/01/17 8:09' with Gradle 3.0
 *
 * @author mati, @date 31/01/17 8:09
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
