/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mati' at '17/01/17 10:40' with Gradle 3.0
 *
 * @author mati, @date 17/01/17 10:40
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
